# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "dcf0ff631f3b80de06acf67c730c3ad5"
name = "Order Manager"
application_url = "https://shopify-order-manager.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,write_orders,read_all_orders"

[auth]
redirect_urls = [ 
  "https://shopify-order-manager.onrender.com/api/auth/callback",
  "https://shopify-order-manager.onrender.com/api/auth"
]