# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "dcf0ff631f3b80de06acf67c730c3ad5"
application_url = "https://shopify-order-manager.onrender.com"
embedded = true
name = "Order Manager"

[access_scopes]
# Added read_customers scope to allow fetching order buyer information
scopes = "read_products, read_orders, write_orders, read_customers"

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

[auth]
redirect_urls = [ 
  "https://shopify-order-manager.onrender.com/api/auth/callback",
  "https://shopify-order-manager.onrender.com/api/auth"
]

[build]
automatically_update_urls_on_dev = true
